name: sync
on:
  push:
    branches: 'main'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
        
      - name: Chekout remote repo
        uses: actions/checkout@v4
        with:
          repository: NorDevLab/nordevlab.github.io
          ref: 'main'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          path: repo-site
      
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          path: repo-site-current
          
      - name: Copy and push
        run: |
          rm -rf repo-site-current/.github && \
          rm -rf repo-site-current/.git && \
          mv * repo-site-current/* repo-site/ && \
          cd repo-site && \
          git config user.name "GitHub Actions Bot"
          git config user.email "foo@bar.com"
          #ls
          #cd repo-site-current
          ls -lah
          
      #- run: git add . && git commit -am 'sync'
      #- run: git push origin main
      #- run: cd repo-site && pwd && ls -la
