name: sync
on:
  push:
    branches: 'main'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: create folder
        run: mkdir repo-site
        
      - uses: actions/checkout@v4
        with:
          repository: NorDevLab/nordevlab.github.io
          ref: 'main'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          dir: repo-site
                
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "foo@bar.com"
      #- run: git add . && git commit -am 'sync'
      #- run: git push origin main
      - run: cd repo-site && ls -lah && pwd
