name: sync
on:
  push:
    branches: 'main'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: NorDevLab/nordevlab.github.io
          ref: 'main'
          token:  ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - run: git add . && git commit -am 'sync'
      - run: git push origin main
